[tool.poetry]
name = "repl_nix_bst-visualizer"
version = "0.1.0"
description = ""
authors = ["Replit user <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
Flask-RESTful = "^0.3.9"
binarytree = "^6.5.1"
Flask = "^2.2.2"
keyboard = "^0.13.5"
ibm-watson = "^7.0.0"
Flask-Cors = "^4.0.0"
lxml = "^4.9.3"
bs4 = "^0.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
